name=eva-filters
version=0.0.1
author=Andrey Gusev
maintainer=Andrey Gusev
sentence=EVA Filters.
paragraph=Signal filtering library: Median, Exponential Smooth, Adaptive Smooth, Slew Rate, MinMax, and Sliding Window filters.
category=Data Processing
url=https://github.com/agusevtec/eva-filters
architectures=*
includes=evafFilters.h
depends=eva-core-sk
