name=eva-filters
version=1.0.1
author=Andrey Gusev
maintainer=Andrey Gusev
sentence=EVA Filters. Signal filtering library: Median, Exponential Moving Average, Adaptive Exponential Moving Average, Slew Rate Limiter, Morphological Min-max and open-close.
paragraph=
category=Data Processing
url=https://github.com/agusevtec/eva-filters
architectures=*
includes=evafFilters.h
depends=eva-core-sk
